### ISSUE TITLE
PSUControl v1.0.0

### ISSUE THREAD

**Issue by kantlivelong** [SimplyPrint/OctoPrint-SimplyPowerController#2]
Hello,

Just wanted to let you know that the recent v1.0.0 release of PSU Control supports events, helpers, and sub plugins. You may no longer need to maintain a fork.

See https://github.com/kantlivelong/OctoPrint-PSUControl/wiki/Developers for more info.

**Comment by AlbertMN** [comment]
Hey, thanks so much for thinking of us, and for letting us know! Will take a deeper look to see that all the stuff we need is there, but looks promising!

**Comment by AlbertMN** [comment]
Took a while, but support for PSUControl has now been implemented, and is live in `SimplyPrint Cloud v3.1.0` which was just released. Thanks for adding the dev. stuff!
